USE [mawatta]
ALTER TABLE [dbo].[commande] REBUILD PARTITION = 1 WITH(DATA_COMPRESSION = ROW )
USE [mawatta]
ALTER TABLE [dbo].[commande] REBUILD PARTITION = 2 WITH(DATA_COMPRESSION = ROW )
USE [mawatta]
ALTER TABLE [dbo].[commande] REBUILD PARTITION = 3 WITH(DATA_COMPRESSION = ROW )
USE [mawatta]
ALTER TABLE [dbo].[commande] REBUILD PARTITION = 4 WITH(DATA_COMPRESSION = ROW )

