--CREATE MASTER KEY ENCRYPTION BY PASSWORD='Password123!'
--CREATE CERTIFICATE cERTMSSQL WITH SUBJECT='Formation Alphorm'
--BACKUP CERTIFICATE cERTMSSQL TO FILE='C:\bkp\bkp_certMSSQL.cert'

CREATE DATABASE db_crypte