USE test
--CREATE MASTER KEY ENCRYPTION BY PASSWORD='password123!'

--OPEN MASTER KEY  DECRYPTION BY PASSWORD='123!'

--CLOSE MASTER KEY
--CREATE CERTIFICATE certTest WITH SUBJECT='Formation Alphorm'

BACKUP CERTIFICATE certTest TO FILE='C:\bkp\bkp_cert_test.cert'